python main.py --log_dir /tmp/sac/noisy/2_features/run0 --random_seed 0 &
python main.py --log_dir /tmp/sac/noisy/2_features/run1 --random_seed 1 &
python main.py --log_dir /tmp/sac/noisy/2_features/run2 --random_seed 2 &
python main.py --log_dir /tmp/sac/noisy/2_features/run3 --random_seed 3 &
python main.py --log_dir /tmp/sac/noisy/2_features/run4 --random_seed 4 &
python main.py --log_dir /tmp/sac/noisy/2_features/run5 --random_seed 5 &
python main.py --log_dir /tmp/sac/noisy/2_features/run6 --random_seed 6 &
python main.py --log_dir /tmp/sac/noisy/2_features/run7 --random_seed 7 &
python main.py --log_dir /tmp/sac/noisy/2_features/run8 --random_seed 8 &
python main.py --log_dir /tmp/sac/noisy/2_features/run9 --random_seed 9 &